### ISSUE TITLE
isLocked is afaik not a real field

### ISSUE THREAD

**Issue by lukaspj** [Areloch/GG-Torque3D#28]
This line here:
https://github.com/Areloch/Torque3D/blob/BaseGameTemplate/Templates/BaseGame/game/core/lighting/advanced/shadowViz.cs#L78
Uses ".isLocked" but I haven't been able to locate where that field is defined. Should it just be ".Locked"?

**Comment by Azaezel** [comment]
https://github.com/GarageGames/Torque3D/search?utf8=%E2%9C%93&q=isLocked
somebody accidentally drop the () maybe?

**Comment by Areloch** [comment]
Yeah, changed it to use the function, not a fake-field ;)
