### ISSUE TITLE
serverToClientObject does not seem to be defined anywhere

### ISSUE THREAD

**Issue by lukaspj** [Areloch/GG-Torque3D#29]
Found it used here:
https://github.com/Areloch/Torque3D/blob/BaseGameTemplate/Templates/BaseGame/game/core/lighting/advanced/shadowViz.cs#L84

**Comment by Azaezel** [comment]
https://github.com/GarageGames/Torque3D/blob/c83efa59e0a11fc15c68afaf106807643191ac6f/Templates/Empty/game/core/scripts/client/client.cs#L39

**Comment by lukaspj** [comment]
Oh, right this issue was meant to be for the BaseGameTemplate branch, doesn't seem like the issues are tied to specific branches though.

Doesn't seem to be defined in the BaseGameTemplate branch is what I meant :P

**Comment by Areloch** [comment]
Added into the core helper functions
