### ISSUE TITLE
Disabling a shape component causes a crash

### ISSUE THREAD

**Issue by crabmusket** [Areloch/GG-Torque3D#3]
I unticked the enable box in the Player shape in the demo level, and got a crash. Haven't looked into it yet.

**Comment by Areloch** [comment]
Ah, looks like a dependency conflict with the animation behavior. When the render shape is disabled, the animation behavior still attempts to updates, but no longer has access to the shape and triggers a crash.

I think we probably need 2 things, 1) get dependency hooks in there(I'd started, but then stopped to work on other stuff) so if one is disabled, the dependent ones are as well and 2) clean up the animation behavior's fetching of the shape component, it's really ugly now.

**Comment by crabmusket** [comment]
Okay, I'll look into this over the next couple days. Sounds like a good way to familiarise myself with the internals of the system.
