### ISSUE TITLE
Where is the pushFront command defined?

### ISSUE THREAD

**Issue by lukaspj** [Areloch/GG-Torque3D#31]
I couldn't find the pushFront command to be defined anywhere.
https://github.com/Areloch/Torque3D/blob/BaseGameTemplate/Templates/BaseGame/game/core/parseArgs.cs#L80

**Comment by Azaezel** [comment]
original def to clone: https://github.com/GarageGames/Torque3D/blob/c83efa59e0a11fc15c68afaf106807643191ac6f/Templates/Empty/game/core/parseArgs.cs#L26

**Comment by Areloch** [comment]
Copied this on over.
