### ISSUE TITLE
MissionGroup musicTrack?

### ISSUE THREAD

**Issue by lukaspj** [Areloch/GG-Torque3D#36]
We send a musicTrack in this line:
https://github.com/Areloch/Torque3D/blob/BaseGameTemplate/Templates/BaseGame/game/data/clientServer/scripts/server/levelDownload.cs#L54
But we do not receive it in the other end, nor use it for anything. It's unused. I think we can safely delete it.

**Comment by Areloch** [comment]
Cleaned up
